# Site settings
title:            "Livida Fitness"
email: danielle@lividafitness.com.au
description: "Livida fitness"
baseurl: ""
url: "http://lividafitness.com.au"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty


# Custom vars
# -------------------------

current_version:  1.0.0
name:         Livida Fitness

# Main Logo
# -------------------------

logo_regular: "/media/logo/logo_regular.png"
logo_small_devices: "/media/logo/logo_small.png"


# Main Navigation Links
# -------------------------

navbar_links:
  - title: "Home"
    url: "#image-hero"
  - title: "Features"
    url: "#features"
  - title: "Services"
    url: "#services"
  - title: "Work"
    url: "#work"    
  - title: "Pricing Tables"
    url: "#pricing-tables"
  - title: "Contact"
    url: "#contact"

# Navigation Background Color. 
# Options: caribbean-green, summer-sky, golden-poppy, deep-carmine-pink
navbar_color: "black"


# Blockquote
# -------------------------

blockquote: 
   button_text: "Contact me"
   button_url: "#contact"

# Services
# -------------------------

services:
 - title: "Early Mornings"
   icon: "desktop"
   description: "Want to get your workout in before you hit the office?  Click here to find out more about my early morning bootcamp sessions in the Inner West."
 - title: "Mums & Bubs, Students & Shift Workers"
   icon: "apple"
   description: "I currently offer a 10am Friday bootcamp at Lysaght Park in Chiswick and welcome all fitness levels.  Get in touch now to join the current term."
 - title: "Evenings"
   icon: "magic"
   description: "Are you a night owl, or only have time in the evenings to work out?  I also offer after work bootcamp sessions.  Click here to find out more."      

# Work Mosaic
# -------------------------

work_thumbs:
 - title: "Maxime Corporis Set"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-01.jpg"
 - title: "Veritatis Vel Recusandae"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-02.jpg"
 - title: "Consectetur Adipisicing"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-03.jpg"
 - title: "Asperiores Soluta"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-04.jpg"
 - title: "Officiis Aspernatur"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-05.jpg"   
 - title: "Soluta Asperiores"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-06.jpg"
 - title: "Adipisicing Consectetur"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-07.jpg"
 - title: "Maxime Corporis Set"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-08.jpg"

# Contact
# -------------------------

contact:
   latitude: "-33.852131"
   longitude: "151.155762"
   marker_title: "Livida Fitness"
   marker_address: "LEVEL 1, 160 VICTORIA ROAD DRUMMOYNE NSW 2047"
   phone_number: "0481 520 740"
   email_address: "danielle@lividafitness.com.au"
   facebook_page: "https://www.facebook.com/lividafitness"

# Configuration
# -------------------------
